export const ORDER={writer:1,editor:2,owner:3};
const TTL=28800;
const enc=v=>{const b=typeof v==='string'?new TextEncoder().encode(v):v;let s='';for(const x of b)s+=String.fromCharCode(x);return btoa(s).replaceAll('+','-').replaceAll('/','_').replaceAll('=','')};
const dec=v=>{v=v.replaceAll('-','+').replaceAll('_','/');v+='='.repeat((4-v.length%4)%4);const s=atob(v);return Uint8Array.from(s,c=>c.charCodeAt(0))};
export function users(env){try{const x=JSON.parse(env.CMS_USERS_JSON||'[]');return Array.isArray(x)?x.filter(u=>u?.username&&u?.passwordHash).map(u=>({username:u.username,displayName:u.displayName||u.username,role:['writer','editor','owner'].includes(u.role)?u.role:'writer',passwordHash:u.passwordHash})):[]}catch{return[]}}
async function mac(secret,s){const k=await crypto.subtle.importKey('raw',new TextEncoder().encode(secret),{name:'HMAC',hash:'SHA-256'},false,['sign']);return new Uint8Array(await crypto.subtle.sign('HMAC',k,new TextEncoder().encode(s)))}
export async function verifyPassword(pass,stored){const p=String(stored||'').split('$');if(p.length!==4||p[0]!=='pbkdf2')return false;const it=Number(p[1]);if(!Number.isFinite(it)||it<100000)return false;try{const k=await crypto.subtle.importKey('raw',new TextEncoder().encode(pass),'PBKDF2',false,['deriveBits']),salt=dec(p[2]),expected=dec(p[3]),actual=new Uint8Array(await crypto.subtle.deriveBits({name:'PBKDF2',salt,iterations:it,hash:'SHA-256'},k,256));return actual.length===expected.length&&actual.every((x,i)=>x===expected[i])}catch{return false}}
export async function issue(env,user){const p=enc(JSON.stringify({username:user.username,displayName:user.displayName,role:user.role,exp:Math.floor(Date.now()/1000)+TTL}));return p+'.'+enc(await mac(env.CMS_SESSION_SECRET,p))}
export async function read(req,env){const c=req.headers.get('cookie')||'',m=c.match(/(?:^|;\s*)tanzimfc_cms=([^;]+)/);if(!m||!env.CMS_SESSION_SECRET)return null;const[p,s]=m[1].split('.');try{const a=await mac(env.CMS_SESSION_SECRET,p),b=dec(s);if(a.length!==b.length||!a.every((x,i)=>x===b[i]))return null;const u=JSON.parse(new TextDecoder().decode(dec(p)));return u.exp>Date.now()/1000?u:null}catch{return null}}
export function sameOrigin(req){const o=req.headers.get('origin');return !o||o===new URL(req.url).origin}
export async function requireUser(req,env,min='writer'){if(!sameOrigin(req))return{error:new Response(JSON.stringify({error:'Invalid origin'}),{status:403,headers:{'content-type':'application/json'}})};const user=await read(req,env);if(!user)return{error:new Response(JSON.stringify({error:'Authentication required'}),{status:401,headers:{'content-type':'application/json'}})};if((ORDER[user.role]||0)<ORDER[min])return{error:new Response(JSON.stringify({error:'Forbidden'}),{status:403,headers:{'content-type':'application/json'}})};return{user}}
export async function login(req,env){if(!sameOrigin(req))return new Response(JSON.stringify({error:'Invalid origin'}),{status:403,headers:{'content-type':'application/json'}});const x=await req.json().catch(()=>null);if(!x?.username||typeof x.password!=='string')return new Response(JSON.stringify({error:'Username and password are required'}),{status:400,headers:{'content-type':'application/json'}});const user=users(env).find(a=>a.username===x.username.trim());if(!user||!await verifyPassword(x.password,user.passwordHash))return new Response(JSON.stringify({error:'Invalid credentials'}),{status:401,headers:{'content-type':'application/json'}});if(!env.CMS_SESSION_SECRET)return new Response(JSON.stringify({error:'CMS_SESSION_SECRET is not configured'}),{status:500,headers:{'content-type':'application/json'}});const token=await issue(env,user);return new Response(JSON.stringify({user:{username:user.username,displayName:user.displayName,role:user.role}}),{headers:{'content-type':'application/json','set-cookie':`tanzimfc_cms=${token}; Path=/; HttpOnly; Secure; SameSite=Lax; Max-Age=${TTL}`}})}
export function logout(){return new Response(JSON.stringify({ok:true}),{headers:{'content-type':'application/json','set-cookie':'tanzimfc_cms=; Path=/; HttpOnly; Secure; SameSite=Lax; Max-Age=0'}})}
export {TTL};
