import { Octokit } from 'octokit';
const OWNER='TanzimFC',REPO='fcmobiletools',BRANCH='main',DIR='src/content/blog';
const MANAGED=new Set(['id','slug','title','description','excerpt','subtitle','type','category','author','status','createdBy','createdAt','updatedAt','publishedAt','image','imageAlt','imageCaption','tags','featured','seoTitle','seoDescription','reviewNotes','draft','difficulty','canonicalUrl','noindex','readingTime','relatedArticles','relatedTools','relatedCodes','sources','lastReviewed','reviewer']);
export const cleanSlug=v=>String(v||'').trim().toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-+|-+$/g,'').slice(0,120);
const safe=v=>String(v||'').replace(/[^a-zA-Z0-9._-]/g,''),now=()=>new Date().toISOString();
const quote=v=>JSON.stringify(String(v??'')),arr=v=>JSON.stringify(Array.isArray(v)?v.filter(Boolean).map(String):[]);
const b64=s=>{let x='';for(const b of new TextEncoder().encode(s))x+=String.fromCharCode(b);return btoa(x)};
const file=(s,ext='.md')=>`${DIR}/${safe(s)}${ext}`,path=p=>p.split('/').map(encodeURIComponent).join('/');
const api=env=>new Octokit({auth:env.GITHUB_TOKEN});
async function get(env,route,params={}){return(await api(env).request(route,{...params,headers:{'x-github-api-version':'2022-11-28'}})).data}
function scalar(v){v=String(v??'').trim();if(v==='null')return '';if(v==='true')return true;if(v==='false')return false;if(/^['\"].*['\"]$/.test(v))try{return JSON.parse(v.replaceAll("'",'\"'))}catch{return v.slice(1,-1)}return v}
function list(v){try{const x=JSON.parse(String(v||'[]').replaceAll("'",'\"'));return Array.isArray(x)?x.map(String):[]}catch{return String(v||'').split(',').map(x=>x.trim()).filter(Boolean)}}
function sanitizeContent(input){let s=String(input||'');s=s.replace(/<\s*(script|style|object|embed|form|input|button|textarea|select|meta|link|base)\b[^>]*>[\s\S]*?<\s*\/\s*\1\s*>/gi,'');s=s.replace(/<\s*(script|style|object|embed|form|input|button|textarea|select|meta|link|base)\b[^>]*\/?>/gi,'');s=s.replace(/\s+on[a-z]+\s*=\s*(?:"[^"]*"|'[^']*'|[^\s>]+)/gi,'');s=s.replace(/\s+(href|src)\s*=\s*(["'])\s*javascript:[\s\S]*?\2/gi,'');s=s.replace(/\s+(href|src)\s*=\s*(["'])\s*data:(?!image\/(?:png|jpe?g|gif|webp);base64,)[\s\S]*?\2/gi,'');return s}
export function parse(raw,name){let f={},fm='',body=raw;if(raw.startsWith('---\n')){const i=raw.indexOf('\n---',4);if(i>0){fm=raw.slice(4,i);body=raw.slice(i+4).replace(/^\n/,'');for(const line of fm.split('\n')){const m=line.match(/^([A-Za-z][\w]*)\s*:\s*(.*)$/);if(!m)continue;const k=m[1];f[k]=['tags','relatedPlayers','relatedEvents','relatedArticles','relatedTools','relatedCodes','sources'].includes(k)?list(m[2]):scalar(m[2])}}}return{slug:String(f.slug||name.replace(/\.mdx?$/i,'')),title:String(f.title||''),excerpt:String(f.excerpt||f.description||''),description:String(f.description||f.excerpt||''),subtitle:String(f.subtitle||''),content:body,author:String(f.author||''),category:String(f.category||'Guides'),image:String(f.image||''),imageAlt:String(f.imageAlt||''),imageCaption:String(f.imageCaption||''),tags:Array.isArray(f.tags)?f.tags:[],seoTitle:String(f.seoTitle||''),seoDescription:String(f.seoDescription||''),publishedAt:String(f.publishedAt||''),updatedAt:String(f.updatedAt||''),createdAt:String(f.createdAt||''),status:String(f.status||'draft'),createdBy:String(f.createdBy||''),reviewNotes:String(f.reviewNotes||''),type:String(f.type||'guide'),featured:Boolean(f.featured),draft:Boolean(f.draft),difficulty:String(f.difficulty||''),canonicalUrl:String(f.canonicalUrl||''),noindex:Boolean(f.noindex),readingTime:Number(f.readingTime)||0,relatedArticles:Array.isArray(f.relatedArticles)?f.relatedArticles:[],relatedTools:Array.isArray(f.relatedTools)?f.relatedTools:[],relatedCodes:Array.isArray(f.relatedCodes)?f.relatedCodes:[],sources:Array.isArray(f.sources)?f.sources:[],lastReviewed:String(f.lastReviewed||''),reviewer:String(f.reviewer||''),_frontmatter:fm,_fileName:name}}
function managedLines(p){const st=['draft','review','scheduled','published','archived'].includes(p.status)?p.status:'draft';const ty=['news','guide','player-review','ranking','analysis','event-guide','explanation','opinion'].includes(p.type)?p.type:'guide';const lines=[`id: ${quote(p.slug)}`,`slug: ${quote(p.slug)}`,`title: ${quote(p.title)}`,`description: ${quote(p.description||p.excerpt)}`,`excerpt: ${quote(p.excerpt)}`,`subtitle: ${quote(p.subtitle)}`,`type: ${ty}`,`category: ${quote(p.category||'Guides')}`,`author: ${quote(p.author||'TanzimFC')}`,`status: ${st}`,`createdBy: ${quote(p.createdBy)}`,`createdAt: ${quote(p.createdAt||now())}`,`updatedAt: ${quote(p.updatedAt||now())}`];if(p.publishedAt)lines.push(`publishedAt: ${quote(p.publishedAt)}`);return lines.concat([`image: ${quote(p.image)}`,`imageAlt: ${quote(p.imageAlt)}`,`imageCaption: ${quote(p.imageCaption)}`,`tags: ${arr(p.tags)}`,`featured: ${Boolean(p.featured)}`,`seoTitle: ${quote(p.seoTitle)}`,`seoDescription: ${quote(p.seoDescription)}`,`reviewNotes: ${quote(p.reviewNotes)}`,`difficulty: ${quote(p.difficulty)}`,`canonicalUrl: ${quote(p.canonicalUrl)}`,`noindex: ${Boolean(p.noindex)}`,`readingTime: ${Number(p.readingTime)||0}`,`relatedArticles: ${arr(p.relatedArticles)}`,`relatedTools: ${arr(p.relatedTools)}`,`relatedCodes: ${arr(p.relatedCodes)}`,`sources: ${arr(p.sources)}`,`lastReviewed: ${quote(p.lastReviewed)}`,`reviewer: ${quote(p.reviewer)}`,`draft: ${st!=='published'}`])}
export function serialize(p){const preserved=String(p._frontmatter||'').split('\n').filter(line=>{const m=line.match(/^([A-Za-z][\w]*)\s*:/);return !m||!MANAGED.has(m[1])});return['---',...managedLines(p),...preserved.filter(Boolean),'---','',sanitizeContent(p.content),''].join('\n')}
export async function readPost(env,slug){let lastError;for(let attempt=0;attempt<5;attempt++){for(const ext of ['.md','.mdx'])try{const p=file(slug,ext),x=await get(env,`GET /repos/${OWNER}/${REPO}/contents/${path(p)}`,{ref:BRANCH}),raw=new TextDecoder().decode(Uint8Array.from(atob(String(x.content).replace(/\n/g,'')),c=>c.charCodeAt(0)));return{file:x,post:parse(raw,p)}}catch(e){lastError=e}if(attempt<4)await new Promise(r=>setTimeout(r,350*(attempt+1)))}throw lastError||new Error('Post not found')}
export async function writePost(env,p,sha,ext='.md'){const pth=file(p.slug,ext),params={owner:OWNER,repo:REPO,path:pth,message:`${sha?'Update':'Create'} article: ${p.title}`,content:b64(serialize(p)),branch:BRANCH};if(sha)params.sha=sha;return(await api(env).rest.repos.createOrUpdateFileContents(params)).data}
export async function listPosts(env,user){let lastError;for(let attempt=0;attempt<5;attempt++){try{const items=await get(env,`GET /repos/${OWNER}/${REPO}/contents/${path(DIR)}`,{ref:BRANCH}),files=(Array.isArray(items)?items:[]).filter(item=>item.type==='file'&&/\.mdx?$/i.test(item.name));const results=await Promise.all(files.map(async item=>{try{const x=await readPost(env,item.name.replace(/\.mdx?$/i,''));if(user.role==='writer'&&x.post.createdBy&&x.post.createdBy!==user.username)return null;return{...x.post,sha:x.file.sha,extension:x.file.name.endsWith('.mdx')?'.mdx':'.md'}}catch{return null}}));return results.filter(Boolean).sort((a,b)=>String(b.updatedAt||b.publishedAt||'').localeCompare(String(a.updatedAt||a.publishedAt||'')))}catch(e){lastError=e}if(attempt<4)await new Promise(r=>setTimeout(r,350*(attempt+1)))}throw new Error(`Could not list articles: ${lastError?.message||'GitHub request failed'}`)}
export async function deletePost(env,p,sha,ext='.md'){const pth=file(p.slug,ext);return(await api(env).rest.repos.deleteFile({owner:OWNER,repo:REPO,path:pth,message:`Delete article: ${p.title}`,sha,branch:BRANCH})).data}
