import { Octokit } from 'octokit';
const OWNER='TanzimFC',REPO='fcmobiletools',BRANCH='main',DIR='src/content/blog';
export const cleanSlug=v=>String(v||'').trim().toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-+|-+$/g,'').slice(0,120);
const safe=v=>String(v||'').replace(/[^a-zA-Z0-9._-]/g,''),now=()=>new Date().toISOString();
const quote=v=>JSON.stringify(String(v??'')),arr=v=>JSON.stringify(Array.isArray(v)?v.filter(Boolean).map(String):[]);
const b64=s=>{let x='';for(const b of new TextEncoder().encode(s))x+=String.fromCharCode(b);return btoa(x)};
const file=s=>`${DIR}/${safe(s)}.md`,path=p=>p.split('/').map(encodeURIComponent).join('/');
const api=env=>new Octokit({auth:env.GITHUB_TOKEN});
async function get(env,route,params={}){return (await api(env).request(route,{...params,headers:{'x-github-api-version':'2022-11-28'}})).data}
function scalar(v){v=String(v??'').trim();if(v==='null')return '';if(v==='true')return true;if(v==='false')return false;if(/^['\"].*['\"]$/.test(v))try{return JSON.parse(v.replaceAll("'",'\"'))}catch{return v.slice(1,-1)}return v}
function list(v){try{const x=JSON.parse(String(v||'[]').replaceAll("'",'\"'));return Array.isArray(x)?x.map(String):[]}catch{return String(v||'').split(',').map(x=>x.trim()).filter(Boolean)}}
export function parse(raw,name){let f={},body=raw;if(raw.startsWith('---\n')){const i=raw.indexOf('\n---',4);if(i>0){body=raw.slice(i+4).replace(/^\n/,'');for(const line of raw.slice(4,i).split('\n')){const m=line.match(/^([A-Za-z][\w]*)\s*:\s*(.*)$/);if(!m)continue;const k=m[1];f[k]=['tags','relatedPlayers','relatedEvents','relatedArticles','relatedTools','relatedCodes','sources'].includes(k)?list(m[2]):scalar(m[2])}}}return{slug:String(f.slug||name.replace(/\.mdx?$/i,'')),title:String(f.title||''),excerpt:String(f.excerpt||f.description||''),description:String(f.description||f.excerpt||''),content:body,author:String(f.author||''),category:String(f.category||'Guides'),image:String(f.image||''),imageAlt:String(f.imageAlt||''),imageCaption:String(f.imageCaption||''),tags:Array.isArray(f.tags)?f.tags:[],seoTitle:String(f.seoTitle||''),seoDescription:String(f.seoDescription||''),publishedAt:String(f.publishedAt||''),updatedAt:String(f.updatedAt||''),createdAt:String(f.createdAt||''),status:String(f.status||'draft'),createdBy:String(f.createdBy||''),reviewNotes:String(f.reviewNotes||''),type:String(f.type||'guide'),featured:Boolean(f.featured),draft:Boolean(f.draft)}}
export function serialize(p){const st=['draft','review','scheduled','published','archived'].includes(p.status)?p.status:'draft',ty=['news','guide','player-review','ranking','analysis','event-guide','explanation','opinion'].includes(p.type)?p.type:'guide';return['---',`id: ${quote(p.slug)}`,`slug: ${quote(p.slug)}`,`title: ${quote(p.title)}`,`description: ${quote(p.description||p.excerpt)}`,`excerpt: ${quote(p.excerpt)}`,`type: ${ty}`,`category: ${quote(p.category||'Guides')}`,`author: ${quote(p.author||'TanzimFC')}`,`status: ${st}`,`createdBy: ${quote(p.createdBy)}`,`createdAt: ${quote(p.createdAt||now())}`,`updatedAt: ${quote(p.updatedAt||now())}`,`publishedAt: ${quote(p.publishedAt)}`,`image: ${quote(p.image)}`,`imageAlt: ${quote(p.imageAlt)}`,`imageCaption: ${quote(p.imageCaption)}`,`tags: ${arr(p.tags)}`,'relatedPlayers: []','relatedEvents: []','relatedArticles: []','relatedTools: []','relatedCodes: []',`featured: ${Boolean(p.featured)}`,`seoTitle: ${quote(p.seoTitle)}`,`seoDescription: ${quote(p.seoDescription)}`,`reviewNotes: ${quote(p.reviewNotes)}`,'sources: []',`draft: ${st!=='published'}`,'---','',String(p.content||'').replace(/\s+$/g,''),''].join('\n')}
export async function readPost(env,slug){const p=file(slug),x=await get(env,`GET /repos/${OWNER}/${REPO}/contents/${path(p)}`,{ref:BRANCH}),raw=new TextDecoder().decode(Uint8Array.from(atob(String(x.content).replace(/\n/g,'')),c=>c.charCodeAt(0)));return{file:x,post:parse(raw,p)}}
export async function writePost(env,p,sha){const pth=file(p.slug),params={owner:OWNER,repo:REPO,path:pth,message:`${sha?'Update':'Create'} article: ${p.title}`,content:b64(serialize(p)),branch:BRANCH};if(sha)params.sha=sha;return(await api(env).rest.repos.createOrUpdateFileContents(params)).data}
export async function listPosts(env,user){const items=await get(env,`GET /repos/${OWNER}/${REPO}/contents/${path(DIR)}`,{ref:BRANCH}),out=[];for(const item of(Array.isArray(items)?items:[])){if(item.type!=='file'||!/.mdx?$/i.test(item.name))continue;try{const x=await readPost(env,item.name.replace(/\.mdx?$/i,''));if(user.role==='writer'&&x.post.createdBy&&x.post.createdBy!==user.username)continue;out.push({...x.post,sha:x.file.sha})}catch{}}return out.sort((a,b)=>String(b.updatedAt||b.publishedAt).localeCompare(String(a.updatedAt||a.publishedAt)))}
