import { Octokit } from 'octokit';
const OWNER='TanzimFC',REPO='fcmobiletools',BRANCH='main',PATH='src/data/redeem-codes.json',STATIC_PATH='src/data/redeemCodes.js';
const api=env=>new Octokit({auth:env.GITHUB_TOKEN});
const b64=s=>{let x='';for(const b of new TextEncoder().encode(s))x+=String.fromCharCode(b);return btoa(x)};
const dec=s=>new TextDecoder().decode(Uint8Array.from(atob(String(s).replace(/\n/g,'')),c=>c.charCodeAt(0)));
const now=()=>new Date().toISOString();
const STATUSES=new Set(['active','expired','unknown']);
const seeded=[{code:'ZlATANWORLDPREMIERE',reward:'117 Zlatan Player Item',status:'active',releaseDate:'2026-09-16',expiryDate:null,region:'Global',lastVerified:'2026-09-16',notes:''}];
function normalize(input,existing){const status=STATUSES.has(input.status)?input.status:(existing?.status&&STATUSES.has(existing.status)?existing.status:'unknown');return{id:String(existing?.id||input.id||`rc_${crypto.randomUUID().replace(/-/g,'').slice(0,12)}`),code:String(input.code??existing?.code??'').trim(),reward:String(input.reward??existing?.reward??''),status,releaseDate:String(input.releaseDate??existing?.releaseDate??''),expiryDate:input.expiryDate?String(input.expiryDate):(existing?.expiryDate??null),region:String(input.region??existing?.region??'Global'),redeemUrl:String(input.redeemUrl??existing?.redeemUrl??''),notes:String(input.notes??existing?.notes??''),lastVerified:String(input.lastVerified??existing?.lastVerified??''),deleted:typeof input.deleted==='boolean'?input.deleted:Boolean(existing?.deleted??false),updatedAt:String(input.updatedAt??existing?.updatedAt??''),updatedBy:String(input.updatedBy??existing?.updatedBy??'')}}
async function getFile(env,path){const r=await api(env).request(`GET /repos/${OWNER}/${REPO}/contents/${path}`,{ref:BRANCH,headers:{'x-github-api-version':'2022-11-28'}});return{sha:r.data.sha,text:dec(r.data.content)}}
async function readCodes(env){try{const r=await getFile(env,PATH);const codes=JSON.parse(r.text);return{codes:Array.isArray(codes)?codes:[],sha:r.sha}}catch(e){if(e?.status===404)return{codes:seed(),sha:null};throw e}}
function seed(){return seeded.map((x,i)=>normalize({...x,id:`rc_seed_${String(i+1).padStart(4,'0')}`},{id:`rc_seed_${String(i+1).padStart(4,'0')}`}))}
function staticModule(codes){const publicCodes=codes.filter(c=>!c.deleted).map(c=>({code:c.code,reward:c.reward,status:c.status,releaseDate:c.releaseDate,expiryDate:c.expiryDate,region:c.region,lastVerified:c.lastVerified,notes:c.notes}));return`// FC Mobile redeem-code database.\n// This file is generated automatically by the CMS when redeem codes change.\n// Do not edit manually; use the Redeem Codes section in /admin.\nexport const REDEEM_CODES = ${JSON.stringify(publicCodes,null,2)};\n\nexport const REDEEM_STATUS = {\n  active: { label: 'Active', className: 'active' },\n  expired: { label: 'Expired', className: 'expired' },\n  unknown: { label: 'Unknown', className: 'unknown' },\n};\n`}
async function saveFile(env,path,content,sha,message){const p={owner:OWNER,repo:REPO,path,message,content:b64(content),branch:BRANCH};if(sha)p.sha=sha;return(await api(env).rest.repos.createOrUpdateFileContents(p)).data}
async function writeCodes(env,codes,sha,message){const json=await saveFile(env,PATH,JSON.stringify(codes,null,2)+'\n',sha,message);const stat=await getFile(env,STATIC_PATH);const staticResult=await saveFile(env,STATIC_PATH,staticModule(codes),stat.sha,`${message} (public static data)`);return{jsonCommit:json.commit?.sha||null,staticCommit:staticResult.commit?.sha||null}}
export async function createCode(env,input,user){const code=String(input.code||'').trim();if(!code)throw new Error('Code is required');const{codes,sha}=await readCodes(env);if(codes.some(c=>String(c.code||'').toLowerCase()===code.toLowerCase()&&!c.deleted))throw new Error('A code with this text already exists');const entry=normalize({...input,code},{id:`rc_${crypto.randomUUID().replace(/-/g,'').slice(0,12)}`});entry.updatedAt=now();entry.updatedBy=user.username;const commit=await writeCodes(env,[entry,...codes],sha,`Redeem codes: add ${code}`);return{entry,commit}}
export async function updateCode(env,id,input,user){const{codes,sha}=await readCodes(env),idx=codes.findIndex(c=>c.id===id);if(idx===-1)throw new Error('Code not found');const entry=normalize(input,codes[idx]);entry.updatedAt=now();entry.updatedBy=user.username;const next=[...codes];next[idx]=entry;const commit=await writeCodes(env,next,sha,`Redeem codes: ${entry.deleted?'hide':'update'} ${entry.code}`);return{entry,commit}}
export async function listCodes(env){const{codes}=await readCodes(env);return codes.sort((a,b)=>String(b.updatedAt||b.lastVerified||'').localeCompare(String(a.updatedAt||a.lastVerified||'')))}
