import { Octokit } from 'octokit';
import { REDEEM_CODES as LEGACY_CODES } from '../data/redeemCodes.js';

const OWNER='TanzimFC',REPO='fcmobiletools',BRANCH='main',PATH='src/data/redeem-codes.json';
const api=env=>new Octokit({auth:env.GITHUB_TOKEN});
const b64=s=>{let x='';for(const b of new TextEncoder().encode(s))x+=String.fromCharCode(b);return btoa(x)};
const now=()=>new Date().toISOString();
const STATUSES=new Set(['active','expired']);
function normalize(input,existing){return{ id:String(existing?.id||input.id||''), code:String(input.code??existing?.code??'').trim(), reward:String(input.reward??existing?.reward??''), status:STATUSES.has(input.status)?input.status:(existing?.status||'active'), releaseDate:String(input.releaseDate??existing?.releaseDate??''), expiryDate:input.expiryDate?String(input.expiryDate):(existing?.expiryDate??null), region:String(input.region??existing?.region??'Global'), redeemUrl:String(input.redeemUrl??existing?.redeemUrl??''), notes:String(input.notes??existing?.notes??''), lastVerified:String(input.lastVerified??existing?.lastVerified??''), deleted:Boolean(existing?.deleted??false)} }
async function readGitHub(env){const res=await api(env).request(`GET /repos/${OWNER}/${REPO}/contents/${PATH}`,{ref:BRANCH,headers:{'x-github-api-version':'2022-11-28'}});const raw=new TextDecoder().decode(Uint8Array.from(atob(String(res.data.content).replace(/\n/g,'')),c=>c.charCodeAt(0)));const codes=JSON.parse(raw);return{codes:Array.isArray(codes)?codes:[],sha:res.data.sha}}
function legacyCode(x,i){return{id:x.id||`rc_seed_${String(i+1).padStart(4,'0')}`,code:String(x.code||''),reward:String(x.reward||''),status:STATUSES.has(x.status)?x.status:'expired',releaseDate:String(x.releaseDate||''),expiryDate:x.expiryDate||null,region:String(x.region||'Global'),redeemUrl:String(x.redeemUrl||''),notes:String(x.notes||''),lastVerified:String(x.lastVerified||''),deleted:false,updatedAt:'',updatedBy:'migration'}}
export async function readCodes(env){try{const r=await readGitHub(env),byCode=new Map(LEGACY_CODES.map((x,i)=>[String(x.code||'').toLowerCase(),legacyCode(x,i)]));for(const x of r.codes){const key=String(x.code||'').toLowerCase();if(key)byCode.set(key,x)}return{codes:Array.from(byCode.values()),sha:r.sha}}catch(e){if(e?.status===404)return{codes:LEGACY_CODES.map(legacyCode),sha:null};throw e}}
async function writeCodes(env,codes,sha,message){const params={owner:OWNER,repo:REPO,path:PATH,message,content:b64(JSON.stringify(codes,null,2)+'\n'),branch:BRANCH};if(sha)params.sha=sha;return(await api(env).rest.repos.createOrUpdateFileContents(params)).data}
export async function createCode(env,input,user){const code=String(input.code||'').trim();if(!code)throw new Error('Code is required');const {codes,sha}=await readCodes(env);if(codes.some(c=>String(c.code||'').toLowerCase()===code.toLowerCase()&&!c.deleted))throw new Error('A code with this text already exists');const entry=normalize({...input,code},{id:'rc_'+crypto.randomUUID().replace(/-/g,'').slice(0,12)});entry.updatedAt=now();entry.updatedBy=user.username;const commit=await writeCodes(env,[entry,...codes],sha,`Redeem codes: add ${code}`);return{entry,commit}}
export async function updateCode(env,id,input,user){const {codes,sha}=await readCodes(env),idx=codes.findIndex(c=>c.id===id);if(idx===-1)throw new Error('Code not found');const entry=normalize(input,codes[idx]);entry.deleted=typeof input.deleted==='boolean'?input.deleted:codes[idx].deleted;entry.updatedAt=now();entry.updatedBy=user.username;const next=[...codes];next[idx]=entry;const commit=await writeCodes(env,next,sha,`Redeem codes: update ${entry.code}`);return{entry,commit}}
export async function listCodes(env){const {codes}=await readCodes(env);return codes.sort((a,b)=>String(b.updatedAt||b.lastVerified||'').localeCompare(String(a.updatedAt||a.lastVerified||'')))}
