const USERS=[
  {username:'tanzimfc',displayName:'TanzimFC',role:'owner',active:true,passwordHash:'pbkdf2$100000$b3wpSqam58XboUnVShyIaA$Ow5qhpgkDFJjV1gfUeywMuvcLhDoAwf1WBh6t11VkfM',sessionVersion:3},
  {username:'tanzimfcm',displayName:'TanzimFC (mobile)',role:'writer',active:true,passwordHash:'pbkdf2$100000$lOt2_B3ca5GGTUHsOtwNJA$68MPLqMQWj8r78IkP7Fha2g0unHBWsls5mEjTnMcTG0',sessionVersion:2}
];
const clean=u=>({username:String(u.username||'').trim().toLowerCase(),displayName:String(u.displayName||u.username||'').trim(),role:['writer','editor','owner'].includes(String(u.role))?String(u.role):'writer',active:u.active!==false,passwordHash:String(u.passwordHash||''),sessionVersion:Number(u.sessionVersion)>0?Number(u.sessionVersion):1});
export async function listUsers(){return USERS.map(clean)}
export async function findUser(_env,username){const wanted=String(username||'').trim().toLowerCase();return USERS.map(clean).find(u=>u.username===wanted&&u.active)||null}
const dec64=v=>{v=String(v||'').replaceAll('-','+').replaceAll('_','/');v+='='.repeat((4-v.length%4)%4);return Uint8Array.from(atob(v),c=>c.charCodeAt(0))};
const enc=v=>{const b=typeof v==='string'?new TextEncoder().encode(v):v;let s='';for(const x of b)s+=String.fromCharCode(x);return btoa(s).replaceAll('+','-').replaceAll('/','_').replaceAll('=','')};
export async function hashPassword(pass){const salt=crypto.getRandomValues(new Uint8Array(16)),key=await crypto.subtle.importKey('raw',new TextEncoder().encode(String(pass)),'PBKDF2',false,['deriveBits']),bits=await crypto.subtle.deriveBits({name:'PBKDF2',salt,iterations:100000,hash:'SHA-256'},key,256);return `pbkdf2$100000$${enc(salt)}$${enc(new Uint8Array(bits))}`}
export async function verifyPassword(pass,stored){const p=String(stored||'').split('$');if(p.length!==4||p[0]!=='pbkdf2'||Number(p[1])<1)return false;try{const key=await crypto.subtle.importKey('raw',new TextEncoder().encode(String(pass)),'PBKDF2',false,['deriveBits']),salt=dec64(p[2]),expected=dec64(p[3]),actual=new Uint8Array(await crypto.subtle.deriveBits({name:'PBKDF2',salt,iterations:Number(p[1]),hash:'SHA-256'},key,256));if(actual.length!==expected.length)return false;let diff=0;for(let i=0;i<actual.length;i++)diff|=actual[i]^expected[i];return diff===0}catch{return false}}
