name = "tanzimfc"
compatibility_date = "2026-09-11"
main = "./src/worker.mjs"
keep_vars = true
workers_dev = true
compatibility_flags = ["nodejs_compat"]

[assets]
directory = "./dist"
binding = "ASSETS"
run_worker_first = [ "/api/*", "/admin", "/admin/*", "/redeem-codes", "/redeem-codes/", "/team-ovr", "/team-ovr/*", "/events", "/events/*", "/reset-center", "/reset-center/*", "/fc-mobile-beta", "/fc-mobile-beta/*", "/players", "/players/*", "/player", "/player/*" ]
not_found_handling = "404-page"
[[routes]]
pattern = "fcmobiletools.online"
custom_domain = true

[[routes]]
pattern = "www.fcmobiletools.online"
custom_domain = true

[[d1_databases]]
binding = "DB"
database_name = "fcmobiletools-content"
database_id = "b54ead2b-0b7f-4daf-8e0b-d9eb1ebce98e"

[secrets]
required = [ "SUPABASE_SECRET_KEY" ]
