const $=s=>document.querySelector(s);const app=$('#app');const status=$('#status');
async function api(path,options={}){const r=await fetch('/api/admin'+path,{credentials:'same-origin',...options});const b=await r.json().catch(()=>({}));if(r.status===401){location.replace('/admin/');throw Error('Session expired.')}if(!r.ok)throw Error(b.error||`Request failed (${r.status}).`);return b}
function msg(text,ok=false){status.textContent=text;status.className=ok?'ok':'error'}
async function overview(){app.innerHTML='<div class="card"><h2>Admin dashboard</h2><p>Use the sections to manage redeem codes, Football Centre content, and Cloudinary media.</p></div>'}
async function redeem(){const {codes}=await api('/redeem');app.innerHTML=`<div class="panel"><h2>Redeem Codes</h2><div class="grid"><label>Code<input id="code"></label><label>Reward<input id="reward"></label><label>Status<select id="codeStatus"><option>active</option><option>scheduled</option><option>expired</option></select></label><label>Release date<input id="releaseDate" type="date"></label><label>Expiry date<input id="expiryDate" type="date"></label><label>Region<input id="region" value="Global"></label></div><button class="primary" id="saveCode">Save code</button><p>${codes.length} codes loaded from GitHub.</p></div><div class="panel"><h3>Existing codes</h3><div>${codes.map(x=>`<div>${x.code} — ${x.reward} — ${x.status}</div>`).join('')}</div></div>`;$('#saveCode').onclick=async()=>{try{const b=await api('/redeem',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({code:$('#code').value,reward:$('#reward').value,status:$('#codeStatus').value,releaseDate:$('#releaseDate').value,expiryDate:$('#expiryDate').value||null,region:$('#region').value})});msg(`Saved. Commit ${b.commitSha}`,true)}catch(e){msg(e.message)}}}
async function football(){const {content}=await api('/football');const clubs=Object.entries(content.clubs);app.innerHTML=`<div class="panel"><h2>Football Centre</h2>${clubs.map(([id,c])=>`<div class="grid"><label>${id} name<input data-id="${id}" data-k="name" value="${c.name}"></label><label>Short name<input data-id="${id}" data-k="short" value="${c.short}"></label><label>Logo URL<input data-id="${id}" data-k="logo" value="${c.logo}"></label></div>`).join('')}<label>Video embed URL<input id="embed" value="${content.videoEmbedUrl}"></label><label>Video watch URL<input id="watch" value="${content.videoWatchUrl}"></label><button class="primary" id="saveFootball">Save Football Centre</button></div>`;$('#saveFootball').onclick=async()=>{try{for(const [id,c] of clubs){for(const k of ['name','short','logo'])content.clubs[id][k]=document.querySelector(`[data-id="${id}"][data-k="${k}"]`).value.trim()}content.videoEmbedUrl=$('#embed').value.trim();content.videoWatchUrl=$('#watch').value.trim();const b=await api('/football',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({content})});msg(`Saved. Commit ${b.commitSha}`,true)}catch(e){msg(e.message)}}}
async function media(){app.innerHTML='<div class="panel"><h2>Media Library</h2><input id="upload" type="file" accept="image/*"><div id="media" class="media"></div></div>';try{const {resources}=await api('/media');$('#media').innerHTML=resources.map(x=>`<div><img src="${x.url}" alt=""><button data-url="${x.url}">Copy URL</button></div>`).join('')||'<p>No Cloudinary images found.</p>';document.querySelectorAll('[data-url]').forEach(b=>b.onclick=()=>navigator.clipboard.writeText(b.dataset.url))}catch(e){$('#media').innerHTML=`<p class="error">${e.message}</p>`}$('#upload').onchange=async e=>{const file=e.target.files[0];if(!file)return;try{const p=await api('/media/sign');const form=new FormData();form.append('file',file);form.append('api_key',p.apiKey);form.append('timestamp',p.timestamp);form.append('folder',p.folder);form.append('signature',p.signature);const r=await fetch(`https://api.cloudinary.com/v1_1/${p.cloudName}/image/upload`,{method:'POST',body:form});const b=await r.json().catch(()=>({}));if(!r.ok)throw Error(b?.error?.message||`Upload failed (${r.status}).`);msg('Upload complete.',true);media()}catch(x){msg(x.message)}}}
async function load(section){$('#title').textContent=section==='overview'?'Overview':section==='redeem'?'Redeem Codes':section==='football'?'Football Centre':'Media Library';try{await ({overview,redeem,football,media}[section])()}catch(e){app.innerHTML=`<div class="card error">${e.message}</div>`}}
document.querySelectorAll('[data-section]').forEach(b=>b.onclick=()=>load(b.dataset.section));$('#logout').onclick=async()=>{await api('/logout',{method:'POST'});location.replace('/admin/')};load('overview');
