import { cp, mkdir, rm, access } from 'node:fs/promises';
import path from 'node:path';
import { execFile } from 'node:child_process';
import { promisify } from 'node:util';
const exec=promisify(execFile);const root=process.cwd();const publicDir=path.join(root,'public');const distDir=path.join(root,'dist');
await mkdir(path.join(publicDir,'assets'),{recursive:true});
await cp(path.join(root,'assets'),path.join(publicDir,'assets'),{recursive:true,force:true});
await rm(path.join(publicDir,'trivia'),{recursive:true,force:true});
await exec('node',['scripts/apply-admin-content.mjs'],{cwd:root});
await exec('node',['scripts/prepare-legacy.mjs'],{cwd:root});
const astroBin=path.join(root,'node_modules','.bin',process.platform==='win32'?'astro.cmd':'astro');
await exec(astroBin,['build'],{cwd:root});
await access(path.join(distDir,'_worker.js','index.js'));
console.log('Astro Cloudflare worker entry verified.');
await cp(path.join(root,'admin'),path.join(distDir,'admin'),{recursive:true,force:true});
for(const file of ['dashboard.html','login.html','rank-up.html','fc-mobile-27.html']) await access(path.join(distDir,'admin',file));
console.log('Astro build complete. Admin assets verified in dist/admin.');
