-- Player catalog foundation. Apply through the repository's Supabase migration workflow.
create extension if not exists pg_trgm with schema extensions;
create extension if not exists unaccent with schema extensions;

create or replace function public.player_search_key(value text)
returns text
language sql
immutable
parallel safe
as $$ select lower(extensions.unaccent(coalesce(value, ''))) $$;

create table if not exists public.players (
  id bigint generated by default as identity primary key,
  player_id bigint not null unique,
  name text not null,
  normalized_name text generated always as (public.player_search_key(name)) stored,
  slug text not null unique,
  ovr smallint not null check (ovr between 1 and 150),
  position text not null,
  alternate_positions text[] not null default '{}',
  club text,
  league text,
  nation text,
  event text,
  skill_moves smallint check (skill_moves between 1 and 5),
  weak_foot smallint check (weak_foot between 1 and 5),
  strong_foot text,
  strong_foot_side text,
  work_rate_attack text,
  work_rate_defense text,
  height_cm smallint check (height_cm between 100 and 250),
  weight_kg smallint check (weight_kg between 30 and 200),
  date_added date,
  is_untradable boolean,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.player_stats (
  player_id bigint primary key references public.players(player_id) on delete cascade,
  stats jsonb not null default '{}'::jsonb,
  source_url text,
  source_name text,
  verified_at timestamptz,
  updated_at timestamptz not null default now(),
  check (jsonb_typeof(stats) = 'object')
);

create table if not exists public.player_ranks (
  player_id bigint not null references public.players(player_id) on delete cascade,
  rank smallint not null check (rank between 0 and 5),
  training_level smallint not null default 0 check (training_level between 0 and 30),
  ovr smallint check (ovr between 1 and 160),
  rank_asset_key text,
  stat_modifiers jsonb not null default '{}'::jsonb,
  source_url text,
  updated_at timestamptz not null default now(),
  primary key (player_id, rank, training_level)
);

create table if not exists public.player_prices (
  id bigint generated by default as identity primary key,
  player_id bigint not null references public.players(player_id) on delete cascade,
  rank smallint not null default 0 check (rank between 0 and 5),
  region text not null default 'global',
  currency text not null default 'coins',
  lowest_sell_price bigint check (lowest_sell_price is null or lowest_sell_price >= 0),
  current_sell_price bigint check (current_sell_price is null or current_sell_price >= 0),
  highest_sell_price bigint check (highest_sell_price is null or highest_sell_price >= 0),
  source_name text not null,
  source_url text not null,
  usage_policy text not null default 'unverified',
  observed_at timestamptz not null,
  created_at timestamptz not null default now(),
  check (current_sell_price is not null or lowest_sell_price is not null or highest_sell_price is not null)
);

create table if not exists public.player_shard_costs (
  id bigint generated by default as identity primary key,
  player_id bigint not null references public.players(player_id) on delete cascade,
  event text not null,
  event_phase text,
  shard_type text not null default 'star_shard',
  shard_cost integer not null check (shard_cost >= 0),
  source_name text not null,
  source_url text not null,
  usage_policy text not null default 'unverified',
  observed_at timestamptz not null,
  created_at timestamptz not null default now(),
  unique (player_id, event, event_phase, shard_type, observed_at)
);

create table if not exists public.player_assets (
  asset_key text primary key,
  player_id bigint references public.players(player_id) on delete cascade,
  asset_type text not null check (asset_type in ('player_image','card_background','nation_flag','club_badge','league_logo','event_art','playstyle','trait','rank','currency','ui_icon')),
  local_path text,
  public_url text,
  source_name text not null,
  source_url text not null,
  license text not null,
  attribution text,
  checksum_sha256 text,
  created_at timestamptz not null default now(),
  check (local_path is not null or public_url is not null)
);

create table if not exists public.player_abilities (
  id bigint generated by default as identity primary key,
  name text not null,
  slug text not null unique,
  ability_type text not null check (ability_type in ('playstyle','trait','skill')),
  is_plus boolean not null default false,
  asset_key text references public.player_assets(asset_key) on delete set null,
  description text
);

create table if not exists public.player_ability_links (
  player_id bigint not null references public.players(player_id) on delete cascade,
  ability_id bigint not null references public.player_abilities(id) on delete cascade,
  rank smallint not null default 0 check (rank between 0 and 5),
  primary key (player_id, ability_id, rank)
);

create index if not exists players_name_search_idx on public.players using gin (normalized_name extensions.gin_trgm_ops);
create index if not exists players_ovr_idx on public.players (ovr desc) where is_active;
create index if not exists players_position_ovr_idx on public.players (position, ovr desc) where is_active;
create index if not exists players_event_idx on public.players (event) where is_active;
create index if not exists players_club_idx on public.players (club) where is_active;
create index if not exists players_league_idx on public.players (league) where is_active;
create index if not exists players_nation_idx on public.players (nation) where is_active;
create index if not exists player_prices_latest_idx on public.player_prices (player_id, rank, region, observed_at desc);
create index if not exists player_shard_costs_event_idx on public.player_shard_costs (event, event_phase, shard_cost);
create index if not exists player_ability_links_ability_idx on public.player_ability_links (ability_id, player_id);

-- Public clients can read active player data; writes require the trusted admin claim.
do $$ declare tbl text; begin
  foreach tbl in array array['players','player_stats','player_ranks','player_prices','player_shard_costs','player_assets','player_abilities','player_ability_links'] loop
    execute format('alter table public.%I enable row level security', tbl);
    execute format('drop policy if exists "public read active player data" on public.%I', tbl);
    execute format('drop policy if exists "admin manage player data" on public.%I', tbl);
    execute format('create policy "public read active player data" on public.%I for select to anon, authenticated using (true)', tbl);
    execute format('create policy "admin manage player data" on public.%I for all to authenticated using ((select auth.jwt() -> ''app_metadata'' ->> ''role'') = ''admin'') with check ((select auth.jwt() -> ''app_metadata'' ->> ''role'') = ''admin'')', tbl);
  end loop;
end $$;

grant select on public.players, public.player_stats, public.player_ranks, public.player_prices,
  public.player_shard_costs, public.player_assets, public.player_abilities, public.player_ability_links
  to anon, authenticated;
grant insert, update, delete on public.players, public.player_stats, public.player_ranks, public.player_prices,
  public.player_shard_costs, public.player_assets, public.player_abilities, public.player_ability_links
  to authenticated;
grant usage, select on all sequences in schema public to authenticated;
