-- Tournament infrastructure
create table if not exists public.tournaments (
  id bigint generated by default as identity primary key,
  slug text not null unique check (slug ~ '^[a-z0-9]+(?:-[a-z0-9]+)*$'),
  name text not null, description text not null default '',
  format smallint not null check (format in (8,16,32)),
  status text not null default 'draft' check (status in ('draft','published','in_progress','completed','cancelled')),
  is_public boolean not null default false,
  starts_at timestamptz, settings jsonb not null default '{}'::jsonb,
  owner_key text not null, published_at timestamptz, completed_at timestamptz,
  created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);
create table if not exists public.tournament_players (
  id bigint generated by default as identity primary key,
  tournament_id bigint not null references public.tournaments(id) on delete cascade,
  slot smallint not null check (slot between 1 and 32),
  display_name text not null, player_tag text not null default '', avatar_url text not null default '',
  seed smallint check (seed is null or seed between 1 and 32),
  status text not null default 'active' check (status in ('active','withdrawn')),
  metadata jsonb not null default '{}'::jsonb, created_at timestamptz not null default now(), updated_at timestamptz not null default now(),
  unique (tournament_id, slot), unique (tournament_id, seed)
);
create table if not exists public.tournament_matches (
  id bigint generated by default as identity primary key,
  tournament_id bigint not null references public.tournaments(id) on delete cascade,
  round_number smallint not null check (round_number between 1 and 5),
  match_number smallint not null check (match_number between 1 and 16),
  player1_id bigint references public.tournament_players(id) on delete restrict,
  player2_id bigint references public.tournament_players(id) on delete restrict,
  player1_score integer check (player1_score is null or player1_score >= 0),
  player2_score integer check (player2_score is null or player2_score >= 0),
  winner_player_id bigint references public.tournament_players(id) on delete restrict,
  status text not null default 'scheduled' check (status in ('scheduled','ready','live','completed')),
  next_match_id bigint references public.tournament_matches(id) on delete set null,
  next_slot smallint check (next_slot is null or next_slot in (1,2)),
  started_at timestamptz, completed_at timestamptz, created_at timestamptz not null default now(), updated_at timestamptz not null default now(),
  unique (tournament_id, round_number, match_number)
);
create table if not exists public.tournament_audit_log (
  id bigint generated by default as identity primary key,
  tournament_id bigint references public.tournaments(id) on delete cascade,
  actor_key text not null, actor_role text not null check (actor_role in ('admin','organizer')),
  action text not null, payload jsonb not null default '{}'::jsonb, created_at timestamptz not null default now()
);
create table if not exists public.tournament_publications (
  id bigint generated by default as identity primary key,
  tournament_id bigint not null unique references public.tournaments(id) on delete cascade,
  git_commit_sha text, published_at timestamptz not null default now(), snapshot_hash text, updated_at timestamptz not null default now()
);
create index if not exists tournaments_public_directory_idx on public.tournaments (is_public,status,updated_at desc);
create index if not exists tournament_players_tournament_idx on public.tournament_players (tournament_id,slot);
create index if not exists tournament_matches_tournament_idx on public.tournament_matches (tournament_id,round_number,match_number);
create index if not exists tournament_audit_tournament_idx on public.tournament_audit_log (tournament_id,created_at desc);
alter table public.tournaments enable row level security;
alter table public.tournament_players enable row level security;
alter table public.tournament_matches enable row level security;
alter table public.tournament_audit_log enable row level security;
alter table public.tournament_publications enable row level security;
revoke all on public.tournaments,public.tournament_players,public.tournament_matches,public.tournament_audit_log,public.tournament_publications from anon,authenticated;
grant all on public.tournaments,public.tournament_players,public.tournament_matches,public.tournament_audit_log,public.tournament_publications to service_role;
grant usage,select on all sequences in schema public to service_role;

create or replace function public.save_tournament_draft(p_payload jsonb) returns bigint
language plpgsql security invoker set search_path=public as $$
declare t_id bigint; p jsonb; t_format integer; t_name text; t_slug text;
begin
 t_id:=nullif(p_payload->>'id','')::bigint; t_name:=trim(coalesce(p_payload->>'name','')); t_slug:=trim(coalesce(p_payload->>'slug','')); t_format:=(p_payload->>'format')::integer;
 if t_name='' then raise exception 'Tournament name is required.'; end if;
 if t_format not in (8,16,32) then raise exception 'Tournament format must be 8, 16, or 32.'; end if;
 if t_slug='' then raise exception 'Tournament slug is required.'; end if;
 if t_id is null then
  insert into public.tournaments(slug,name,description,format,status,is_public,starts_at,settings,owner_key,updated_at)
  values(t_slug,t_name,coalesce(p_payload->>'description',''),t_format,'draft',coalesce((p_payload->>'isPublic')::boolean,false),nullif(p_payload->>'startsAt','')::timestamptz,coalesce(p_payload->'settings','{}'::jsonb),coalesce(p_payload->>'ownerKey','organizer'),now()) returning id into t_id;
 else
  update public.tournaments set slug=t_slug,name=t_name,description=coalesce(p_payload->>'description',''),format=t_format,is_public=coalesce((p_payload->>'isPublic')::boolean,false),starts_at=nullif(p_payload->>'startsAt','')::timestamptz,settings=coalesce(p_payload->'settings','{}'::jsonb),updated_at=now() where id=t_id;
  if not found then raise exception 'Tournament not found.'; end if;
 end if;
 if exists(select 1 from public.tournament_matches where tournament_id=t_id) then raise exception 'A bracket already exists. Tournament details cannot be reseeded after bracket generation.'; end if;
 delete from public.tournament_players where tournament_id=t_id;
 for p in select * from jsonb_array_elements(coalesce(p_payload->'players','[]'::jsonb)) loop
  insert into public.tournament_players(tournament_id,slot,display_name,player_tag,avatar_url,seed,metadata)
  values(t_id,(p->>'slot')::smallint,trim(coalesce(p->>'displayName','')),trim(coalesce(p->>'playerTag','')),coalesce(p->>'avatarUrl',''),nullif(p->>'seed','')::smallint,coalesce(p->'metadata','{}'::jsonb));
 end loop;
 return t_id;
end $$;
create or replace function public.generate_tournament_bracket(p_tournament_id bigint) returns jsonb
language plpgsql security invoker set search_path=public as $$
declare t public.tournaments%rowtype; active_count integer; existing_matches integer; seed_order integer[]:=array[1,2]; next_order integer[]; i integer;j integer;n integer;round_count integer:=0;total_matches integer:=0;p1 bigint;p2 bigint;
begin
 select * into t from public.tournaments where id=p_tournament_id for update; if not found then raise exception 'Tournament not found.'; end if;
 if t.status in ('completed','cancelled') then raise exception 'This tournament can no longer generate a bracket.'; end if;
 select count(*) into active_count from public.tournament_players where tournament_id=p_tournament_id and status='active';
 if active_count<>t.format then raise exception 'Tournament requires exactly % active players. Currently has %.',t.format,active_count; end if;
 select count(*) into existing_matches from public.tournament_matches where tournament_id=p_tournament_id; if existing_matches>0 then raise exception 'A bracket already exists.'; end if;
 n:=4; while n<=t.format loop next_order:='{}'; for i in 1..coalesce(array_length(seed_order,1),0) loop next_order:=array_append(next_order,seed_order[i]); next_order:=array_append(next_order,n+1-seed_order[i]); end loop; seed_order:=next_order;n:=n*2;end loop;
 round_count:=floor(log(t.format::numeric)/log(2::numeric));
 for i in 1..(t.format/2) loop
  p1:=(select id from public.tournament_players where tournament_id=p_tournament_id and slot=seed_order[(i*2)-1] and status='active' limit 1);
  p2:=(select id from public.tournament_players where tournament_id=p_tournament_id and slot=seed_order[i*2] and status='active' limit 1);
  insert into public.tournament_matches(tournament_id,round_number,match_number,player1_id,player2_id,status) values(p_tournament_id,1,i,p1,p2,case when p1 is not null and p2 is not null then 'ready' else 'scheduled' end); total_matches:=total_matches+1;
 end loop;
 for j in 2..round_count loop for i in 1..(t.format/power(2,j))::integer loop insert into public.tournament_matches(tournament_id,round_number,match_number,status) values(p_tournament_id,j,i,'scheduled'); total_matches:=total_matches+1; end loop; end loop;
 update public.tournament_matches m set next_match_id=n.id,next_slot=case when m.match_number%2=1 then 1 else 2 end,updated_at=now() from public.tournament_matches n where m.tournament_id=p_tournament_id and n.tournament_id=p_tournament_id and n.round_number=m.round_number+1 and n.match_number=ceil(m.match_number::numeric/2.0)::smallint;
 update public.tournaments set updated_at=now() where id=p_tournament_id;
 return jsonb_build_object('ok',true,'tournamentId',p_tournament_id,'format',t.format,'rounds',round_count,'matches',total_matches);
end $$;
create or replace function public.record_tournament_result(p_match_id bigint,p_player1_score integer,p_player2_score integer) returns jsonb
language plpgsql security invoker set search_path=public as $$
declare m public.tournament_matches%rowtype; winner_id bigint; final_match boolean:=false; next_ready boolean; tournament_status text;
begin
 if p_player1_score is null or p_player2_score is null or p_player1_score<0 or p_player2_score<0 then raise exception 'Scores must be non-negative integers.'; end if;
 if p_player1_score=p_player2_score then raise exception 'A draw cannot advance a player. Enter the final match score.'; end if;
 select * into m from public.tournament_matches where id=p_match_id for update; if not found then raise exception 'Match not found.'; end if;
 if m.status='completed' then raise exception 'This match already has a recorded result.'; end if;
 if m.player1_id is null or m.player2_id is null then raise exception 'Both players must be assigned before entering a result.'; end if;
 winner_id:=case when p_player1_score>p_player2_score then m.player1_id else m.player2_id end;
 update public.tournament_matches set player1_score=p_player1_score,player2_score=p_player2_score,winner_player_id=winner_id,status='completed',completed_at=now(),updated_at=now() where id=p_match_id;
 if m.next_match_id is not null then
  if m.next_slot=1 then update public.tournament_matches set player1_id=winner_id,updated_at=now() where id=m.next_match_id; else update public.tournament_matches set player2_id=winner_id,updated_at=now() where id=m.next_match_id; end if;
  select(player1_id is not null and player2_id is not null) into next_ready from public.tournament_matches where id=m.next_match_id;
  if next_ready then update public.tournament_matches set status=case when status='live' then 'live' else 'ready' end,updated_at=now() where id=m.next_match_id; end if;
 else final_match:=true; end if;
 if final_match then update public.tournaments set status='completed',completed_at=now(),updated_at=now() where id=m.tournament_id; else update public.tournaments set status=case when status in('draft','published') then 'in_progress' else status end,updated_at=now() where id=m.tournament_id; end if;
 select status into tournament_status from public.tournaments where id=m.tournament_id;
 return jsonb_build_object('ok',true,'matchId',m.id,'tournamentId',m.tournament_id,'winnerPlayerId',winner_id,'nextMatchId',m.next_match_id,'final',final_match,'tournamentStatus',tournament_status);
end $$;
revoke all on function public.save_tournament_draft(jsonb),public.generate_tournament_bracket(bigint),public.record_tournament_result(bigint,integer,integer) from public,anon,authenticated;
grant execute on function public.save_tournament_draft(jsonb),public.generate_tournament_bracket(bigint),public.record_tournament_result(bigint,integer,integer) to service_role;
