-- Advanced tournament engine: formats, phases, groups, ties, standings
alter table public.tournaments
  add column if not exists format_key text not null default 'single_elimination',
  add column if not exists participant_count integer not null default 0 check (participant_count between 0 and 5000),
  add column if not exists format_config jsonb not null default '{}'::jsonb;

create table if not exists public.tournament_stages (
  id bigint generated by default as identity primary key,
  tournament_id bigint not null references public.tournaments(id) on delete cascade,
  stage_order smallint not null check (stage_order between 1 and 20),
  stage_key text not null,
  name text not null,
  stage_type text not null check (stage_type in ('league','group','knockout','playoff','placement','swiss')),
  match_mode text not null default 'single' check (match_mode in ('single','home_away','best_of_3','best_of_5')),
  group_count integer check (group_count is null or group_count between 1 and 500),
  teams_per_group integer check (teams_per_group is null or teams_per_group between 2 and 64),
  advance_per_group integer check (advance_per_group is null or advance_per_group between 1 and 32),
  rounds integer check (rounds is null or rounds between 1 and 20),
  config jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (tournament_id, stage_order),
  unique (tournament_id, stage_key)
);

create table if not exists public.tournament_groups (
  id bigint generated by default as identity primary key,
  stage_id bigint not null references public.tournament_stages(id) on delete cascade,
  group_number smallint not null,
  name text not null,
  created_at timestamptz not null default now(),
  unique (stage_id, group_number)
);

alter table public.tournament_matches
  add column if not exists stage_id bigint references public.tournament_stages(id) on delete cascade,
  add column if not exists group_id bigint references public.tournament_groups(id) on delete set null,
  add column if not exists tie_id bigint,
  add column if not exists leg_number smallint not null default 1,
  add column if not exists matchday smallint,
  add column if not exists home_score integer,
  add column if not exists away_score integer,
  add column if not exists extra_time boolean not null default false,
  add column if not exists penalties_home integer,
  add column if not exists penalties_away integer;

create table if not exists public.tournament_ties (
  id bigint generated by default as identity primary key,
  tournament_id bigint not null references public.tournaments(id) on delete cascade,
  stage_id bigint references public.tournament_stages(id) on delete cascade,
  tie_number integer not null,
  player1_id bigint references public.tournament_players(id) on delete restrict,
  player2_id bigint references public.tournament_players(id) on delete restrict,
  legs_required smallint not null default 1 check (legs_required in (1,2,3,5)),
  status text not null default 'scheduled' check (status in ('scheduled','ready','live','completed')),
  winner_player_id bigint references public.tournament_players(id) on delete restrict,
  next_tie_id bigint references public.tournament_ties(id) on delete set null,
  next_slot smallint check (next_slot is null or next_slot in (1,2)),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (tournament_id, tie_number)
);

do $$
begin
  if not exists (select 1 from pg_constraint where conname='tournament_matches_tie_id_fkey') then
    alter table public.tournament_matches add constraint tournament_matches_tie_id_fkey
      foreign key (tie_id) references public.tournament_ties(id) on delete cascade;
  end if;
end $$;

create table if not exists public.tournament_standings (
  id bigint generated by default as identity primary key,
  tournament_id bigint not null references public.tournaments(id) on delete cascade,
  stage_id bigint not null references public.tournament_stages(id) on delete cascade,
  group_id bigint references public.tournament_groups(id) on delete cascade,
  player_id bigint not null references public.tournament_players(id) on delete cascade,
  played integer not null default 0,
  wins integer not null default 0,
  draws integer not null default 0,
  losses integer not null default 0,
  goals_for integer not null default 0,
  goals_against integer not null default 0,
  goal_difference integer not null default 0,
  points integer not null default 0,
  rank integer,
  tiebreak jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now(),
  unique (stage_id, group_id, player_id)
);

create index if not exists tournament_stages_tournament_idx on public.tournament_stages(tournament_id, stage_order);
create index if not exists tournament_groups_stage_idx on public.tournament_groups(stage_id, group_number);
create index if not exists tournament_matches_stage_idx on public.tournament_matches(stage_id, matchday, round_number, match_number);
create index if not exists tournament_matches_group_idx on public.tournament_matches(group_id);
create index if not exists tournament_matches_tie_idx on public.tournament_matches(tie_id, leg_number);
create index if not exists tournament_ties_stage_idx on public.tournament_ties(stage_id, tie_number);
create index if not exists tournament_standings_stage_idx on public.tournament_standings(stage_id, group_id, rank);

alter table public.tournament_stages enable row level security;
alter table public.tournament_groups enable row level security;
alter table public.tournament_ties enable row level security;
alter table public.tournament_standings enable row level security;
revoke all on public.tournament_stages, public.tournament_groups, public.tournament_ties, public.tournament_standings from anon, authenticated;
grant all on public.tournament_stages, public.tournament_groups, public.tournament_ties, public.tournament_standings to service_role;

create or replace function public.save_tournament_draft(p_payload jsonb) returns bigint
language plpgsql security invoker set search_path=public as $$
declare t_id bigint; p jsonb; t_format integer; t_name text; t_slug text;
begin
  t_id:=nullif(p_payload->>'id','')::bigint;
  t_name:=trim(coalesce(p_payload->>'name',''));
  t_slug:=trim(coalesce(p_payload->>'slug',''));
  t_format:=coalesce(nullif(p_payload->>'participantCount','')::integer,jsonb_array_length(coalesce(p_payload->'players','[]'::jsonb)));
  if t_name='' then raise exception 'Tournament name is required.'; end if;
  if t_format<2 or t_format>5000 then raise exception 'Tournament must have between 2 and 5000 participants.'; end if;
  if t_slug='' then raise exception 'Tournament slug is required.'; end if;
  if t_id is null then
    insert into public.tournaments(slug,name,description,format,format_key,participant_count,format_config,status,is_public,starts_at,settings,owner_key,updated_at)
    values(t_slug,t_name,coalesce(p_payload->>'description',''),t_format,coalesce(p_payload->>'formatKey','single_elimination'),t_format,coalesce(p_payload->'formatConfig','{}'::jsonb),'draft',coalesce((p_payload->>'isPublic')::boolean,false),nullif(p_payload->>'startsAt','')::timestamptz,coalesce(p_payload->'settings','{}'::jsonb),coalesce(p_payload->>'ownerKey','organizer'),now())
    returning id into t_id;
  else
    if exists(select 1 from public.tournament_matches where tournament_id=t_id) or exists(select 1 from public.tournament_stages where tournament_id=t_id) then
      raise exception 'The tournament structure already exists. Stage settings and participants are locked after generation.';
    end if;
    update public.tournaments set slug=t_slug,name=t_name,description=coalesce(p_payload->>'description',''),format=t_format,format_key=coalesce(p_payload->>'formatKey','single_elimination'),participant_count=t_format,format_config=coalesce(p_payload->'formatConfig','{}'::jsonb),is_public=coalesce((p_payload->>'isPublic')::boolean,false),starts_at=nullif(p_payload->>'startsAt','')::timestamptz,settings=coalesce(p_payload->'settings','{}'::jsonb),updated_at=now() where id=t_id;
    if not found then raise exception 'Tournament not found.'; end if;
  end if;
  delete from public.tournament_players where tournament_id=t_id;
  for p in select * from jsonb_array_elements(coalesce(p_payload->'players','[]'::jsonb)) loop
    insert into public.tournament_players(tournament_id,slot,display_name,player_tag,avatar_url,seed,metadata)
    values(t_id,(p->>'slot')::smallint,trim(coalesce(p->>'displayName','')),trim(coalesce(p->>'playerTag','')),coalesce(p->>'avatarUrl',''),nullif(p->>'seed','')::smallint,coalesce(p->'metadata','{}'::jsonb));
  end loop;
  return t_id;
end $$;

create or replace function public.save_tournament_structure(p_payload jsonb) returns jsonb
language plpgsql security invoker set search_path=public as $$
declare p_tournament_id bigint:=(p_payload->>'tournamentId')::bigint; stage jsonb; grp jsonb; m jsonb; t public.tournaments%rowtype; stage_id bigint; group_id bigint; match_id bigint; tie_id bigint; existing integer; pid bigint; n record;
begin
  select * into t from public.tournaments where id=p_tournament_id for update; if not found then raise exception 'Tournament not found.'; end if;
  select count(*) into existing from public.tournament_matches where tournament_id=p_tournament_id; if existing>0 then raise exception 'Tournament structure already exists.'; end if;
  delete from public.tournament_standings where tournament_id=p_tournament_id;
  delete from public.tournament_matches where tournament_id=p_tournament_id;
  delete from public.tournament_ties where tournament_id=p_tournament_id;
  delete from public.tournament_groups where stage_id in (select id from public.tournament_stages where tournament_id=p_tournament_id);
  delete from public.tournament_stages where tournament_id=p_tournament_id;
  for stage in select * from jsonb_array_elements(coalesce(p_payload->'stages','[]'::jsonb)) loop
    insert into public.tournament_stages(tournament_id,stage_order,stage_key,name,stage_type,match_mode,group_count,teams_per_group,advance_per_group,rounds,config)
    values(p_tournament_id,(stage->>'stageOrder')::smallint,stage->>'stageKey',stage->>'name',stage->>'stageType',coalesce(stage->>'matchMode','single'),nullif(stage->>'groupCount','')::integer,nullif(stage->>'teamsPerGroup','')::integer,nullif(stage->>'advancePerGroup','')::integer,nullif(stage->>'rounds','')::integer,coalesce(stage->'config','{}'::jsonb))
    returning id into stage_id;
    for grp in select * from jsonb_array_elements(coalesce(stage->'groups','[]'::jsonb)) loop
      insert into public.tournament_groups(stage_id,group_number,name) values(stage_id,(grp->>'groupNumber')::smallint,grp->>'name') returning id into group_id;
      for pid in select (jsonb_array_elements_text(coalesce(grp->'playerIds','[]'::jsonb)))::bigint loop
        insert into public.tournament_standings(tournament_id,stage_id,group_id,player_id) values(p_tournament_id,stage_id,group_id,pid) on conflict(stage_id,group_id,player_id) do nothing;
      end loop;
    end loop;
    for pid in select (jsonb_array_elements_text(coalesce(stage->'standingsPlayerIds','[]'::jsonb)))::bigint loop
      if not exists(select 1 from public.tournament_standings s where s.stage_id=stage_id and s.player_id=pid and s.group_id is null) then
        insert into public.tournament_standings(tournament_id,stage_id,group_id,player_id) values(p_tournament_id,stage_id,null,pid);
      end if;
    end loop;
    for m in select * from jsonb_array_elements(coalesce(stage->'matches','[]'::jsonb)) loop
      group_id:=null;
      if m ? 'groupNumber' then select g.id into group_id from public.tournament_groups g where g.stage_id=stage_id and g.group_number=(m->>'groupNumber')::smallint; end if;
      tie_id:=null;
      if m ? 'tieNumber' then
        select id into tie_id from public.tournament_ties where tournament_id=p_tournament_id and tie_number=(m->>'tieNumber')::integer;
        if tie_id is null then
          insert into public.tournament_ties(tournament_id,stage_id,tie_number,player1_id,player2_id,legs_required,status,winner_player_id)
          values(p_tournament_id,stage_id,(m->>'tieNumber')::integer,nullif(m->>'tiePlayer1Id','')::bigint,nullif(m->>'tiePlayer2Id','')::bigint,coalesce((m->>'legsRequired')::smallint,1),case when m->>'winnerPlayerId' is not null then 'completed' when m->>'tiePlayer1Id' is not null and m->>'tiePlayer2Id' is not null then 'ready' else 'scheduled' end,nullif(m->>'winnerPlayerId','')::bigint)
          returning id into tie_id;
        end if;
      end if;
      insert into public.tournament_matches(tournament_id,stage_id,group_id,tie_id,round_number,match_number,matchday,leg_number,player1_id,player2_id,status,winner_player_id,home_score,away_score)
      values(p_tournament_id,stage_id,group_id,tie_id,coalesce((m->>'roundNumber')::smallint,1),coalesce((m->>'matchNumber')::smallint,1),nullif(m->>'matchday','')::smallint,coalesce((m->>'legNumber')::smallint,1),nullif(m->>'player1Id','')::bigint,nullif(m->>'player2Id','')::bigint,coalesce(m->>'status','scheduled'),nullif(m->>'winnerPlayerId','')::bigint,nullif(m->>'homeScore','')::integer,nullif(m->>'awayScore','')::integer);
    end loop;
    update public.tournament_matches tm set next_match_id=n.id,next_slot=case when tm.match_number%2=1 then 1 else 2 end,updated_at=now()
    from public.tournament_matches n where tm.tournament_id=p_tournament_id and n.tournament_id=p_tournament_id and tm.stage_id=stage_id and n.stage_id=stage_id and tm.tie_id is null and tm.round_number+1=n.round_number and n.match_number=ceil(tm.match_number::numeric/2.0)::smallint;
  end loop;
  -- deterministic byes for single-leg knockout matches
  for n in 1..20 loop
    update public.tournament_matches tm set winner_player_id=coalesce(tm.winner_player_id,tm.player1_id),status='completed',completed_at=coalesce(tm.completed_at,now()),updated_at=now()
    where tm.tournament_id=p_tournament_id and tm.tie_id is null and tm.status<>'completed' and ((tm.player1_id is not null and tm.player2_id is null) or (tm.player1_id is null and tm.player2_id is not null));
    update public.tournament_matches tm set player1_id=coalesce(tm.player1_id,p1.winner_player_id),player2_id=coalesce(tm.player2_id,p2.winner_player_id),status=case when coalesce(tm.player1_id,p1.winner_player_id) is not null and coalesce(tm.player2_id,p2.winner_player_id) is not null then 'ready' else tm.status end,updated_at=now()
    from public.tournament_matches p1 join public.tournament_matches p2 on p2.tournament_id=p_tournament_id and p2.next_match_id=tm.id and p2.next_slot=2
    where tm.tournament_id=p_tournament_id and p1.next_match_id=tm.id and p1.next_slot=1 and tm.tie_id is null;
  end loop;
  update public.tournaments set updated_at=now() where id=p_tournament_id;
  return jsonb_build_object('ok',true,'tournamentId',p_tournament_id);
end $$;

create or replace function public.record_tournament_match_result_v2(p_match_id bigint,p_player1_score integer,p_player2_score integer,p_deciding_winner_player_id bigint default null)
returns jsonb language plpgsql security invoker set search_path=public as $$
declare m public.tournament_matches%rowtype; tie public.tournament_ties%rowtype; winner_id bigint; next_ready boolean:=false; final_competition boolean:=false; agg1 integer; agg2 integer; stage_type text; next_tie public.tournament_ties%rowtype;
begin
  if p_player1_score is null or p_player2_score is null or p_player1_score<0 or p_player2_score<0 then raise exception 'Scores must be non-negative integers.'; end if;
  select * into m from public.tournament_matches where id=p_match_id for update; if not found then raise exception 'Match not found.'; end if;
  if m.status='completed' then raise exception 'This match already has a result.'; end if;
  if m.player1_id is null or m.player2_id is null then raise exception 'Both players must be assigned.'; end if;
  update public.tournament_matches set player1_score=p_player1_score,player2_score=p_player2_score,home_score=p_player1_score,away_score=p_player2_score,status='completed',completed_at=now(),updated_at=now() where id=p_match_id;

  select s.stage_type into stage_type from public.tournament_stages s where s.id=m.stage_id;
  if stage_type in ('group','league','swiss') then
    update public.tournament_standings set played=played+1,wins=wins+case when p_player1_score>p_player2_score then 1 else 0 end,draws=draws+case when p_player1_score=p_player2_score then 1 else 0 end,losses=losses+case when p_player1_score<p_player2_score then 1 else 0 end,goals_for=goals_for+p_player1_score,goals_against=goals_against+p_player2_score,points=points+case when p_player1_score>p_player2_score then 3 when p_player1_score=p_player2_score then 1 else 0 end,updated_at=now()
    where stage_id=m.stage_id and group_id=m.group_id and player_id=m.player1_id;
    update public.tournament_standings set played=played+1,wins=wins+case when p_player2_score>p_player1_score then 1 else 0 end,draws=draws+case when p_player1_score=p_player2_score then 1 else 0 end,losses=losses+case when p_player2_score<p_player1_score then 1 else 0 end,goals_for=goals_for+p_player2_score,goals_against=goals_against+p_player1_score,points=points+case when p_player2_score>p_player1_score then 3 when p_player1_score=p_player2_score then 1 else 0 end,updated_at=now()
    where stage_id=m.stage_id and group_id=m.group_id and player_id=m.player2_id;
    update public.tournament_standings set goal_difference=goals_for-goals_against where stage_id=m.stage_id;
    with ranked as (select id,row_number() over(partition by stage_id,group_id order by points desc,goal_difference desc,goals_for desc,player_id) r from public.tournament_standings where stage_id=m.stage_id)
    update public.tournament_standings s set rank=ranked.r from ranked where s.id=ranked.id;
  end if;

  if m.tie_id is not null then
    select * into tie from public.tournament_ties where id=m.tie_id for update;
    if exists(select 1 from public.tournament_matches where tie_id=tie.id and status<>'completed') then
      return jsonb_build_object('ok',true,'matchId',m.id,'tieComplete',false);
    end if;
    select coalesce(sum(case when player1_id=tie.player1_id then player1_score else player2_score end),0),coalesce(sum(case when player1_id=tie.player2_id then player1_score else player2_score end),0)
    into agg1,agg2 from public.tournament_matches where tie_id=tie.id;
    if agg1>agg2 then winner_id=tie.player1_id; elsif agg2>agg1 then winner_id=tie.player2_id; elsif p_deciding_winner_player_id in(tie.player1_id,tie.player2_id) then winner_id=p_deciding_winner_player_id; else raise exception 'Aggregate score is level. Supply the deciding winner after extra time/penalties.'; end if;
    update public.tournament_ties set winner_player_id=winner_id,status='completed',updated_at=now() where id=tie.id;
    if tie.next_tie_id is not null then
      if tie.next_slot=1 then update public.tournament_ties set player1_id=winner_id,updated_at=now() where id=tie.next_tie_id; else update public.tournament_ties set player2_id=winner_id,updated_at=now() where id=tie.next_tie_id; end if;
      select * into next_tie from public.tournament_ties where id=tie.next_tie_id;
      if next_tie.player1_id is not null and next_tie.player2_id is not null then
        update public.tournament_ties set status='ready',updated_at=now() where id=next_tie.id;
        update public.tournament_matches set player1_id=next_tie.player1_id,player2_id=next_tie.player2_id,status='ready',updated_at=now() where tie_id=next_tie.id and leg_number=1;
        update public.tournament_matches set player1_id=next_tie.player2_id,player2_id=next_tie.player1_id,status='ready',updated_at=now() where tie_id=next_tie.id and leg_number=2;
        next_ready:=true;
      end if;
    else
      final_competition:=true; update public.tournaments set status='completed',completed_at=now(),updated_at=now() where id=m.tournament_id;
    end if;
  else
    winner_id:=case when p_player1_score>p_player2_score then m.player1_id else m.player2_id end;
    update public.tournament_matches set winner_player_id=winner_id,updated_at=now() where id=m.id;
    if m.next_match_id is not null then
      if m.next_slot=1 then update public.tournament_matches set player1_id=winner_id,status=case when player2_id is not null then 'ready' else status end,updated_at=now() where id=m.next_match_id;
      else update public.tournament_matches set player2_id=winner_id,status=case when player1_id is not null then 'ready' else status end,updated_at=now() where id=m.next_match_id; end if;
      select(player1_id is not null and player2_id is not null) into next_ready from public.tournament_matches where id=m.next_match_id;
    else final_competition:=true; update public.tournaments set status='completed',completed_at=now(),updated_at=now() where id=m.tournament_id; end if;
  end if;
  return jsonb_build_object('ok',true,'matchId',m.id,'tournamentId',m.tournament_id,'winnerPlayerId',winner_id,'tieComplete',m.tie_id is not null,'nextReady',next_ready,'final',final_competition);
end $$;

revoke all on function public.save_tournament_draft(jsonb),public.save_tournament_structure(jsonb),public.record_tournament_match_result_v2(bigint,integer,integer,bigint) from public,anon,authenticated;
grant execute on function public.save_tournament_draft(jsonb),public.save_tournament_structure(jsonb),public.record_tournament_match_result_v2(bigint,integer,integer,bigint) to service_role;
